### ISSUE TITLE
[FE] Investors distribution panel graph

### ISSUE THREAD

**Issue by gabyteera** [buidlone/frontend#111]

**Comment by BenasVolkovas** [comment]
Get tokens amount that investor has invested already (events from investment pool contract)

Event to use:
`Invest(address indexed caller, uint256 amount)`
caller -> investor
amount -> tokens amount investor has invested in one of his investments (there can be more than 1 investment made per investor)

Get all Investment events:
filter = `investmentPoolContract.filters.Invest()`;
events =  `await investmentPoolContract.queryFilter(filter);`

events will be assigned to the list of objects, which contains `args` key with `caller` and `amount` as child keys for the corresponding values.
