### ISSUE TITLE
[FE] Integrate Investment contract

### ISSUE THREAD

**Issue by matasvosylius** [buidlone/frontend#50]

**Comment by dimonkov** [comment]
All of the type definitions are provided here:
https://tsh.atlassian.net/wiki/spaces/BUID/pages/2598010907/Contracts+ABI+and+functions+DOCS

It is probably necessary to adjust those files for frontend needs.

**Comment by matasvosylius** [comment]
Thank you @dimonkov, however, I'm closing this issue because of task duplication and transferring info to #56
