### ISSUE TITLE
[FE] Invest to project

### ISSUE THREAD

**Issue by matasvosylius** [buidlone/frontend#56]
To invest in the project you will need to call set function in Investment pool SC:

 - `invest( uint256 _amount,  bool _strict)`

  `_invest` function purpose_: allows to invest a specified amount of funds if fundraiser or not last milestone is active
@input  `_amount` Amount of tokens to invest, must be <= approved amount
@input `_strict` true -> if too large amount should revert; false -> if smaller amount should be accepted

NOTE: prior **approval** from user to this contract is required

**Comment by matasvosylius** [comment]
@dimonkov comment about contract abi:

_"All of the type definitions are provided here:
https://tsh.atlassian.net/wiki/spaces/BUID/pages/2598010907/Contracts+ABI+and+functions+DOCS_

_It is probably necessary to adjust those files for frontend needs."_

**Comment by BenasVolkovas** [comment]
Invest a specified amount of funds if the fundraiser or not last milestone is active

`invest(uint256 _amount, bool _strict)`
@input `_amount` tokens amount to invest, must be more than the approved amount
@input `_strict` true -> if too large amount should revert; false -> if smaller amount should be accepted
At the end `Invest()` event is emitted with the user who called the function (`address`) as 1st argument and `_amount` (`uint256`) as 2nd.

NOTE: The user should first approve the smart contract to transfer the tokens from the user's wallet to the contract.

First, get the address of the accepted token. Use `acceptedToken()` function in **Investment Pool**, which returns `address`.
Second, approve the spender with the address of the investor and the amount to invest. Use `approve(address investor, uint256 amount)` function in **Accepted Token Contract** (example Wrapped Ethereum as a super token), which returns a `bool` (indicating whether the operation succeeded)
Third, wait for the transaction confirmation.

Usage in Web
![Image](https://user-images.githubusercontent.com/49361502/193853470-20e7debc-c6e0-4c0f-bed9-2c17756a1c71.png)
![Image](https://user-images.githubusercontent.com/49361502/193853620-668b0c9a-120b-4fe6-8d7a-8195832b4cf8.png)
![Image](https://user-images.githubusercontent.com/49361502/193853751-ecc4f654-b153-41f6-b285-ea21d95ba649.png)
