### ISSUE TITLE
[FE] Stop project

### ISSUE THREAD

**Issue by matasvosylius** [buidlone/frontend#57]
Vote against the project by transferring investor vote tokens to the governance pool contract. Caller - Investor. which have voting tickets. You will need to call a set function in Governance SC:

- `voteAgainst(address _investmentPool, uint256 _amount)`

@input `_investmentPool` investment pool address, to which investor transfers tokens by voting against it.
@input `_amount` tokens amount investor wants to vote with.

Before calling this function investor needs to approve spender with `votingToken.setApprovalForAll(governancePoolAddress, true)`.

**Comment by BenasVolkovas** [comment]
Vote against the project by transfering investor vote tokens to the governance pool contract (set function, which requires transaction confirmation, in governance pool contract).

Before calling this function investor needs to approve the spender with `votingToken.setApprovalForAll(address governancePoolAddress, bool true)`, where `votingToken` is an object of the contract (get from abi and address), `governancePoolAddress` is the `address` of GP and `true`, which indicates that the investor approves the spender.

`voteAgainst(address _investmentPool, uint256 _amount)`
@input `_investmentPool` address of the investment pool
@input `_amount `tokens amount investor wants to vote with

At the end `VoteAgainstProject()` event is emitted with the investment pool (`address`) as 1st argument, investor address, who called the function (`address`) as 2nd and the number of votes the investor transferred (`uint256`) as 3rd.
If a threshold of 51% was reached, `FinishVoting()` event is also emmited with the investment pool (`address`) as argument.

NOTE: _Reverts if status is not active voting, if amount is zero, if investor doesn't own any tokens, if amount is greater than token balance._

Usage in Website
![Image](https://user-images.githubusercontent.com/49361502/193855101-5a48865d-a2ad-4965-a49f-3a3eb28b121e.png)
![Image](https://user-images.githubusercontent.com/49361502/193855728-93ba5dd1-6e83-4c3c-856b-cbba6871d8fb.png)
