### ISSUE TITLE
[FE] Next milestone start date timer

### ISSUE THREAD

**Issue by BenasVolkovas** [buidlone/frontend#76]
Get current time left until next milestone start (get function in investment pool)

Functions to use:
`milestones(uint256 _milestoneId)`
@input `_milestoneId` id of the milestone
@return `Milestone` -> milestone object (https://tsh.atlassian.net/wiki/spaces/BUID/pages/2598010907/Contracts+ABI+and+functions+DOCS+for+FE)

`currentMilestone()`
@return `uint256` -> current milestones id

Get final value (model):
current milestone id = `currentMilestone()`
milestone start = `milestones(`current milestone id`).startDate`
current time = get current time with typescript
time until next milestone = milestone start - current time

Note: when retrieving start date, firstly, `await` for the milestone object to be returned
**Also, next milestone doesn't have the precise time when it will start**. It has a period of 3 days that is why you should add a note near the displayed date that this milestone can actually start 3 days prior the provided date.

Usage in Website
![Image](https://user-images.githubusercontent.com/49361502/193874869-eff0b3e5-a82b-48c3-ae88-dfd0fadadf0f.png)

**Comment by GabijaBeres** [comment]
It's time left till next milestone, so you probably meant
 milestone start = milestones(current milestone id + 1).startDate ?
